# This is an example configuration file
# you can copy it to config.toml to make modifications which will be used.

no_serpent = false  # refers to the scheduling service
no_basilisk = false  # refers to the filtering service

hydra_subscribe_addr = ""  # Leave empty for default
hydra_remote_recv_addr = ""  # Leave empty for default
data_dir = ""  # leave empty to store data in working dir. Should be an absolute path, be careful.

[exts]
core = [ "mod", "meta", "cleanup", "rolemanagement",]  # refers to module names in src/extensions
contrib = [ "dice", "qotw", "activitymetadata",]  # refers to module names in src/contrib_extensions
local = []  # refers to module names in src/local_extensions
global = []  # refers to discord.py extensions which are installed as modules (ie. `jishaku`)

